### ISSUE TITLE
Version available for TimsR

### ISSUE THREAD

**Issue by ShirleyXieYuting** [MatteoLacki/timsr#1]
Hi, I tried to install with `install.packages('TimsR')` according to your .md, however, I received the below error message:

> Installing package into ‘C:/Users/Administrator/Documents/R/win-library/4.0’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘timsr’ is not available for this version of R
> 
> A version of this package for your version of R might be available elsewhere,
> see the ideas at
> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

I am wondering which version I should use in order to install by `install.packages` command?

**Comment by MatteoLacki** [comment]
Dear Shirley,

Apparently the CRAN maintainers deleted our submission for some reason.
But opentimsr works: https://github.com/michalsta/opentims
Please install this first, then install devtools, then timsr from github
<https://github.com/MatteoLacki/timsr> using

library(devtools)

install.packages("opentimsr")
install_github("MatteoLacki/timsr")


This should work.
In the meanwhile, we will try to convince CRAN that timsr is a good package
:)

Very best wishes,

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by fangfeiz** [comment]
Hi Mateusz,

Thanks for providing solution. We also solved ourselves via `install_github` for `oepntimsr` and `timsr` for R version 4.0. Looking forward for a direct installation from CRAN.

Best, Fangfei

**Comment by michalsta** [comment]
It's on CRAN as of now.

Best,
Michał
